"""The Obsidian projection: a readable, linked view of learner state
(contract 0.6; roadmap 2.4).

The vault is FOR THE HUMAN. It is never a scoring source and never how an
agent restores state (the tutor briefing comes from the engine). Two zones:
``memory/`` is fully generated and overwritten -- hand edits are drift and
get flagged, then lost on rebuild; ``notes/`` belongs to the learner and the
engine neither writes nor reads it.

Pages are ORDINARY markdown, deterministic to the byte: stable ordering
everywhere and, deliberately, **no wall clock in any page** -- dates come
from events and schedules, so re-rendering unchanged state reproduces
identical bytes (canon 3). Every page carries frontmatter with
``generated: true``, its declared source (event-sourced learning state vs
SQLite-authoritative operational state -- the hybrid split of canon 5), and
``source_ids``, which makes drift checking mechanical.

``render_pages`` is a pure function from state to ``{relative_path: bytes}``;
``render``/``rebuild``/``check`` are the thin IO around it. Rebuild deletes
orphans (pages whose entity vanished); check re-renders in memory and
compares -- a mismatch is an error, never silently repaired (read-only
commands repair nothing).

Honest gaps, named: error pages wait for ``ERROR_OBSERVED`` (2.8); gate pages
wait for the gates module; the irregular-verbs overview waits for lexeme-form
aggregation.
"""

from __future__ import annotations

from collections import defaultdict
from typing import Any

from english_trainer.kernel.aggregates import list_aggregates
from english_trainer.kernel.clock import Clock, RandomSource
from english_trainer.kernel.encoding import payload_hash
from english_trainer.kernel.envelopes import make_event
from english_trainer.kernel.ids import new_ulid
from english_trainer.kernel.policy import PolicyRegistry
from english_trainer.kernel.store import EventStore
from english_trainer.kernel.uow import UnitOfWork
from english_trainer.scheduler.engine import fold_schedules
from english_trainer.scheduler.policy import SCHEDULER_KIND
from english_trainer.scoring.aggregates import (
    learning_score,
    measured_working_level,
    working_levels,
    xp_ledger,
)
from english_trainer.scoring.engine import fold_scores
from english_trainer.scoring.policy import SCORING_KIND

EVENT_PROJECTION_UPDATED = "memory.projection_updated"

_HEADER_NOTE = "Generated by the engine. Do not edit: manual changes are drift and will be overwritten."


def _frontmatter(source: str, source_ids: list[str], versions: dict[str, str]) -> str:
    lines = ["---", "generated: true", f"source: {source}"]
    lines.append("source_ids:")
    for sid in source_ids:
        lines.append(f"  - {sid}")
    if versions:
        lines.append("pinned_versions:")
        for kind in sorted(versions):
            lines.append(f"  {kind}: {versions[kind]}")
    lines += [f"note: {_HEADER_NOTE}", "---", ""]
    return "\n".join(lines)


def _slug(value: str) -> str:
    return value.replace("/", "-").replace(":", "-")


def render_pages(store: EventStore, registry: PolicyRegistry) -> dict[str, str]:
    """Pure state -> pages. Deterministic bytes; no wall clock anywhere."""
    curriculum_version, program = registry.resolve_active("curriculum")
    versions = {"curriculum": curriculum_version}
    _, scoring_policy = registry.resolve_active(SCORING_KIND)
    _, scheduler_policy = registry.resolve_active(SCHEDULER_KIND)

    scores = fold_scores(store, scoring_policy)
    schedules = fold_schedules(store, scheduler_policy)
    levels = working_levels(scores, program, scoring_policy)
    measured = measured_working_level(levels)
    score = learning_score(scores, program, scoring_policy, measured)
    xp = xp_ledger(store, scoring_policy)

    topics = {str(t.get("id")): t for t in program.get("topics", [])}
    lexicon = {str(u.get("id")): u for u in program.get("lexicon", [])}
    sessions = list_aggregates(store._conn, "session")
    plans = {str(s.get("session_id")): (pid, s) for pid, s, _ in list_aggregates(store._conn, "session_plan")}
    attempts_by_session: dict[str, int] = defaultdict(int)
    for _, attempt, _ in list_aggregates(store._conn, "attempt"):
        attempts_by_session[str(attempt.get("session_id"))] += 1

    pages: dict[str, str] = {}

    def _schedule_lines(target_id: str) -> list[str]:
        lines = []
        for (ref, dimension), schedule in sorted(schedules.items()):
            if ref == target_id:
                lines.append(
                    f"- {dimension}: next review {schedule.next_review_at.date().isoformat()} "
                    f"(interval {schedule.interval_days}d, epoch {schedule.schedule_epoch})"
                )
        return lines or ["- расписание ещё не открыто"]

    def _mastery_lines(target_id: str) -> tuple[str, str | None, list[str]]:
        state = scores.get(target_id)
        if state is None:
            return "NEW", None, ["- нет оценённых измерений"]
        lines = [f"- {dimension}: {value}" for dimension, value in sorted(state.mastery.items())] or [
            "- нет оценённых измерений"
        ]
        stability = str(state.stability_days) if state.stability_days is not None else None
        return state.knowledge_state, stability, lines

    # -- entity pages: a page per topic and per lexical unit (canon 4: page
    # per entity, independent of whether it has been scored yet).
    for target_id in sorted(topics):
        topic = topics[target_id]
        knowledge_state, stability, mastery_lines = _mastery_lines(target_id)
        body = [
            f"# {target_id}",
            "",
            f"**{topic.get('can_do', '')}**",
            "",
            f"- Уровень: {topic.get('cefr')} · трек: [[{_slug(str(topic.get('track')))}]]",
            f"- Состояние знания: **{knowledge_state}**",
            f"- Stability: {stability} дн." if stability else "- Stability: —",
            "",
            "## Mastery",
            *mastery_lines,
            "",
            "## Повторения",
            *_schedule_lines(target_id),
            "",
        ]
        pages[f"topics/{_slug(target_id)}.md"] = _frontmatter(
            "event-sourced", [target_id], versions
        ) + "\n".join(body)
    for target_id in sorted(lexicon):
        unit = lexicon[target_id]
        knowledge_state, _stability, mastery_lines = _mastery_lines(target_id)
        subdir = "chunks" if "chunk" in str(unit.get("type", "")) else "vocabulary"
        body = [
            f"# {unit.get('title', target_id)}",
            "",
            f"- Единица: `{target_id}` ({unit.get('type', '—')})",
            f"- Значение: {unit.get('meaning_ru', '—')}",
            f"- Состояние знания: **{knowledge_state}**",
            "",
            "## Mastery",
            *mastery_lines,
            "",
            "## Повторения",
            *_schedule_lines(target_id),
            "",
        ]
        pages[f"knowledge/{subdir}/{_slug(target_id)}.md"] = _frontmatter(
            "event-sourced", [target_id], versions
        ) + "\n".join(body)

    # -- sessions and plans (SQLite-authoritative operational state)
    for session_id, session, _ in sorted(sessions, key=lambda row: row[0]):
        manifest = session.get("manifest") or {}
        started = str(manifest.get("started_at", ""))[:10] or "0000-00-00"
        year = started[:4]
        plan_info = plans.get(session_id)
        step_lines: list[str] = []
        if plan_info is not None:
            for step in plan_info[1].get("steps", []):
                mark = "x" if step.get("presented_at") else " "
                target = step.get("target_ref") or "free conversation"
                link = f"[[{_slug(str(target))}]]" if step.get("target_ref") else target
                step_lines.append(f"- [{mark}] {step.get('bucket')}/{step.get('step_type')}: {link}")
        body = [
            f"# Сессия {started} · {session_id}",
            "",
            f"- Статус: **{session.get('status')}** · провайдер: {manifest.get('provider', '—')}",
            f"- Попыток записано: {attempts_by_session.get(session_id, 0)}",
            f"- План: [[{_slug(session_id)}-plan]]",
            "",
            "## Шаги",
            *(step_lines or ["- план пуст"]),
            "",
        ]
        pages[f"sessions/{year}/{started}-{_slug(session_id)}.md"] = _frontmatter(
            "operational", [session_id], versions
        ) + "\n".join(body)
        if plan_info is not None:
            plan_id, plan = plan_info
            remaining = plan.get("ledger", {}).get("remaining_seconds")
            body = [
                f"# План сессии {session_id}",
                "",
                f"- Ревизия композиции: {plan.get('composition_revision')}",
                f"- Версия плана: {plan.get('plan_version')}",
                f"- Бюджет: {plan.get('total_seconds')} сек. · осталось: {remaining} сек.",
                f"- Waivers: {', '.join(plan.get('waivers', [])) or '—'}",
                "",
            ]
            pages[f"plans/{_slug(session_id)}-plan.md"] = _frontmatter(
                "operational", [plan_id, session_id], versions
            ) + "\n".join(body)

    # -- reviews by date (event-sourced schedule projection: schedules are a
    # pure fold over the event log, not SQLite-authoritative operational state)
    by_date: dict[str, list[str]] = defaultdict(list)
    for (target_id, dimension), schedule in sorted(schedules.items()):
        by_date[schedule.next_review_at.date().isoformat()].append(
            f"- [[{_slug(target_id)}]] · {dimension} (интервал {schedule.interval_days}д)"
        )
    for date, lines in sorted(by_date.items()):
        pages[f"reviews/{date}.md"] = _frontmatter(
            "event-sourced", [f"reviews:{date}"], versions
        ) + "\n".join([f"# Повторения на {date}", "", *lines, ""])

    # -- dashboards
    skill_lines = [
        f"- **{skill}**: {info['level'] or 'no-data'} (confidence {info['confidence']}, "
        f"{info['active_topics']} активных тем)"
        for skill, info in sorted(levels.items())
    ]
    pages["current/current-level.md"] = _frontmatter("event-sourced", ["scores"], versions) + "\n".join(
        [
            "# Текущий уровень",
            "",
            f"- Измеренный рабочий уровень: **{measured or 'no-data'}** (не выше слабейшего навыка)",
            f"- Learning Score: **{score or 'no-data'}**",
            "",
            "## Навыки",
            *skill_lines,
            "",
        ]
    )

    counts: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    for topic_id, topic in topics.items():
        state = scores.get(topic_id)
        knowledge = state.knowledge_state if state else "NEW"
        counts[str(topic.get("cefr"))][knowledge] += 1
    progress_lines = []
    for level in ("A1", "A2", "B1", "B2", "C1", "C2"):
        row = counts.get(level, {})
        total = sum(row.values())
        touched = total - row.get("NEW", 0)
        progress_lines.append(
            f"- **{level}**: {total} тем · затронуто {touched} · "
            f"ACTIVE+ {row.get('ACTIVE', 0) + row.get('MASTERED', 0)}"
        )
    pages["current/roadmap-progress.md"] = _frontmatter("event-sourced", ["scores"], versions) + "\n".join(
        ["# Прогресс по программе", "", *progress_lines, ""]
    )

    upcoming = sorted(by_date.items())[:5]
    next_lines = [f"- [[{date}]] — {len(items)} целей" for date, items in upcoming]
    pages["current/next-session.md"] = _frontmatter("event-sourced", ["schedules"], versions) + "\n".join(
        [
            "# Следующая сессия",
            "",
            "## Ближайшие повторения",
            *(next_lines or ["- расписаний ещё нет"]),
            "",
        ]
    )

    vocab_lines = [
        f"- [[{_slug(target_id)}]] · {dimension}: {schedule.next_review_at.date().isoformat()}"
        for (target_id, dimension), schedule in sorted(schedules.items())
        if target_id in lexicon
    ]
    pages["current/vocabulary-review.md"] = _frontmatter(
        "event-sourced", ["schedules"], versions
    ) + "\n".join(["# Лексика к повторению", "", *(vocab_lines or ["- пока нечего повторять"]), ""])

    pages["current/recurring-errors.md"] = _frontmatter("event-sourced", ["errors"], versions) + "\n".join(
        [
            "# Повторяющиеся ошибки",
            "",
            "- данных ещё нет: наблюдение ошибок (`ERROR_OBSERVED`) появится в control-доводке (2.8)",
            "",
        ]
    )

    pages["current/learner-profile.md"] = _frontmatter(
        "operational", ["sessions", "xp"], versions
    ) + "\n".join(
        [
            "# Профиль",
            "",
            f"- Сессий: {len(sessions)}",
            f"- XP: **{xp['total']}** за {xp['practice_days']} дн. практики · streak {xp['streak']}",
            f"- Программа: {len(topics)} тем · {len(lexicon)} лекс. единиц (curriculum {curriculum_version})",
            "",
        ]
    )

    return pages


# -- IO around the pure renderer ---------------------------------------------


def render(store: EventStore, registry: PolicyRegistry, memory_dir: Any) -> dict[str, Any]:
    """Write the projection into ``memory/``; returns written/unchanged counts."""
    from pathlib import Path

    root = Path(memory_dir)
    pages = render_pages(store, registry)
    written, unchanged = [], 0
    for relative, content in sorted(pages.items()):
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        data = content.encode("utf-8")
        if path.exists() and path.read_bytes() == data:
            unchanged += 1
            continue
        path.write_bytes(data)
        written.append(relative)
    return {
        "pages": len(pages),
        "written": written,
        "unchanged": unchanged,
        "content_hash": payload_hash({k: pages[k] for k in sorted(pages)}),
    }


def rebuild(store: EventStore, registry: PolicyRegistry, memory_dir: Any) -> dict[str, Any]:
    """Full regenerate + orphan removal: memory/ ends exactly at the render set."""
    from pathlib import Path

    root = Path(memory_dir)
    report = render(store, registry, memory_dir)
    expected = set(render_pages(store, registry))
    removed = []
    if root.is_dir():
        for path in sorted(root.rglob("*.md")):
            relative = path.relative_to(root).as_posix()
            if relative not in expected:
                path.unlink()
                removed.append(relative)
    return {**report, "removed": removed}


def check(store: EventStore, registry: PolicyRegistry, memory_dir: Any) -> dict[str, Any]:
    """Drift check of the generated zone only. Read-only: repairs nothing."""
    from pathlib import Path

    root = Path(memory_dir)
    pages = render_pages(store, registry)
    drifted, missing, extra = [], [], []
    for relative, content in sorted(pages.items()):
        path = root / relative
        if not path.exists():
            missing.append(relative)
        elif path.read_bytes() != content.encode("utf-8"):
            drifted.append(relative)
    if root.is_dir():
        for path in sorted(root.rglob("*.md")):
            relative = path.relative_to(root).as_posix()
            if relative not in pages:
                extra.append(relative)
    return {
        "ok": not (drifted or missing or extra),
        "drifted": drifted,
        "missing": missing,
        "extra": extra,
        "pages": len(pages),
    }


def emit_projection_updated(
    store: EventStore,
    clock: Clock,
    random_source: RandomSource,
    report: dict[str, Any],
    *,
    actor: str = "engine",
) -> None:
    """Publish the update fact (post-commit projection; canon 6)."""
    with UnitOfWork(store, clock) as uow:
        uow.append(
            [
                make_event(
                    id=new_ulid(clock, random_source),
                    type=EVENT_PROJECTION_UPDATED,
                    occurred_at=clock.now(),
                    actor=actor,
                    correlation_id=new_ulid(clock, random_source),
                    payload={
                        "pages": report["pages"],
                        "written": len(report.get("written", [])),
                        "removed": len(report.get("removed", [])),
                        "content_hash": report["content_hash"],
                    },
                )
            ]
        )
