"""The Obsidian projection: a readable, linked view of learner state
(contract 0.6; roadmap 2.4).

The vault is FOR THE HUMAN. It is never a scoring source and never how an
agent restores state (the tutor briefing comes from the engine). Two zones:
``memory/`` is fully generated and overwritten -- hand edits are drift and
get flagged, then lost on rebuild; ``notes/`` belongs to the learner and the
engine neither writes nor reads it.

Pages are ORDINARY markdown, deterministic to the byte: stable ordering
everywhere and, deliberately, **no wall clock in any page** -- dates come
from events and schedules, so re-rendering unchanged state reproduces
identical bytes (canon 3). Every page carries frontmatter with
``generated: true``, its declared source (event-sourced learning state vs
SQLite-authoritative operational state -- the hybrid split of canon 5), and
``source_ids``, which makes drift checking mechanical.

``render_pages`` is a pure function from state to ``{relative_path: bytes}``;
``render``/``rebuild``/``check`` are the thin IO around it. Rebuild deletes
orphans (pages whose entity vanished); check re-renders in memory and
compares -- a mismatch is an error, never silently repaired (read-only
commands repair nothing).

Frames (lexical-system 1c: chunk lexical items carrying ``frame_of``/``carries``)
get the same chunk-zone page as any other chunk, enriched with their slot hint,
contrast, trap and ``carries`` tags, plus a link back to the topic whose form
they carry; topic pages list their own frames grouped by ``carries`` tag. Every
target page (topic or lexical unit) also carries its ``AutomaticityState``
(scoring 3d) -- read-only, via the reducer's public API, never re-derived here
-- and ``current/automaticity.md`` summarises the whole program by state.
Reconstruction texts (curriculum 2d) get a title-line-only section on their
owning topic's page; the full text is authored material, not rendered here.
``ScheduleState.permanent_interleave`` (scheduler 3a: article-tier frames that
never leave the due queue) is read straight off the schedule -- it is marked
on every schedule line and summed on the vocabulary-review dashboard, never
recomputed here.

Honest gaps, named: error pages wait for ``ERROR_OBSERVED`` (2.8); gate pages
wait for the gates module; the irregular-verbs overview waits for lexeme-form
aggregation.
"""

from __future__ import annotations

from collections import defaultdict
from typing import Any

from english_trainer.kernel.aggregates import list_aggregates
from english_trainer.kernel.clock import Clock, RandomSource
from english_trainer.kernel.encoding import payload_hash
from english_trainer.kernel.envelopes import make_event
from english_trainer.kernel.errors import NoActivePolicy
from english_trainer.kernel.ids import new_ulid
from english_trainer.kernel.policy import PolicyRegistry
from english_trainer.kernel.store import EventStore
from english_trainer.kernel.uow import UnitOfWork
from english_trainer.scheduler.engine import fold_schedules
from english_trainer.scheduler.policy import SCHEDULER_KIND
from english_trainer.scoring.aggregates import (
    learning_score,
    measured_working_level,
    placement_levels,
    placement_writing_level,
    working_levels,
    xp_ledger,
)
from english_trainer.scoring.automaticity import (
    AUTOMATIC,
    AUTOMATICITY_KIND,
    DELIBERATE,
    NOT_MEASURED,
    PROCEDURALIZED,
    AutomaticityState,
    fold_automaticity,
)
from english_trainer.scoring.engine import fold_scores
from english_trainer.scoring.policy import SCORING_KIND

EVENT_PROJECTION_UPDATED = "memory.projection_updated"

# Consumed from the learner module via the event log (events are the module
# boundary; memory must not import learner -- tests/architecture allowlist).
LEARNER_LEXICON_ENTRY_ADDED = "learner.lexicon_entry_added"

_HEADER_NOTE = "Generated by the engine. Do not edit: manual changes are drift and will be overwritten."

# Article-tier frame classification (lexical-system 1c, scheduler.md 3a): a
# lexical item whose `frame_of` names a topic under this prefix is injected
# into the scheduler fold as `permanent_interleave_targets` -- the scheduler
# itself never inspects curriculum content.
#
# The canonical statement of this rule is
# `curriculum.service.permanent_interleave_targets`; it cannot be imported
# here, because the layer allowlist (tests/architecture) gives `memory` only
# kernel/scoring/scheduler -- memory reads the program as a plain dict. The
# two must stay in step; a divergence shows up as a projection that disagrees
# with `trainer review due`.
_ARTICLE_FRAME_PREFIX = "grammar.articles."


def _frontmatter(source: str, source_ids: list[str], versions: dict[str, str]) -> str:
    lines = ["---", "generated: true", f"source: {source}"]
    lines.append("source_ids:")
    for sid in source_ids:
        lines.append(f"  - {sid}")
    if versions:
        lines.append("pinned_versions:")
        for kind in sorted(versions):
            lines.append(f"  {kind}: {versions[kind]}")
    lines += [f"note: {_HEADER_NOTE}", "---", ""]
    return "\n".join(lines)


def _slug(value: str) -> str:
    return value.replace("/", "-").replace(":", "-")


def _ppm_percent(ppm: int) -> str:
    """``accuracy_ppm`` (integer parts-per-million) as a floored X.YY% string.

    Pure integer arithmetic -- no float touches the number on its way to the
    page, matching the fold's own "integers only" discipline (scoring 3d),
    even though this is a display value, not a decision-bearing one.
    """
    hundredths = ppm // 100
    whole, frac = divmod(hundredths, 100)
    return f"{whole}.{frac:02d}%"


def render_pages(store: EventStore, registry: PolicyRegistry) -> dict[str, str]:
    """Pure state -> pages. Deterministic bytes; no wall clock anywhere."""
    curriculum_version, program = registry.resolve_active("curriculum")
    versions = {"curriculum": curriculum_version}
    _, scoring_policy = registry.resolve_active(SCORING_KIND)
    _, scheduler_policy = registry.resolve_active(SCHEDULER_KIND)
    # automaticity@1 (scoring 3d) is a separate, optional policy kind: a store
    # that never activated it (e.g. before this policy existed) still renders
    # -- every target simply shows "not measured", never a crash.
    automaticity_version: str | None
    automaticity_policy: dict[str, Any] | None
    try:
        automaticity_version, automaticity_policy = registry.resolve_active(AUTOMATICITY_KIND)
    except NoActivePolicy:
        automaticity_version, automaticity_policy = None, None
    if automaticity_version is not None:
        versions[AUTOMATICITY_KIND] = automaticity_version

    scores = fold_scores(store, scoring_policy)

    topics = {str(t.get("id")): t for t in program.get("topics", [])}
    lexicon = {str(u.get("id")): u for u in program.get("lexicon", [])}
    sessions = list_aggregates(store._conn, "session")
    plans = {str(s.get("session_id")): (pid, s) for pid, s, _ in list_aggregates(store._conn, "session_plan")}
    attempts_by_session: dict[str, int] = defaultdict(int)
    for _, attempt, _ in list_aggregates(store._conn, "attempt"):
        attempts_by_session[str(attempt.get("session_id"))] += 1

    # -- frames (lexical-system 1c): chunk items carrying `frame_of`, grouped
    # under the topic whose grammatical form they carry.
    frames_by_topic: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for lex_id in sorted(lexicon):
        frame_of = lexicon[lex_id].get("frame_of")
        if frame_of:
            frames_by_topic[str(frame_of)].append(lexicon[lex_id])

    # permanent_interleave (scheduler 3a, PD-F): the scheduler fold stays pure
    # and never touches curriculum content -- classification is injected as a
    # plain frozenset, computed here from the SAME program dict frames_by_topic
    # was built from (no `english_trainer.curriculum` import: memory reads the
    # program as a dict, per the layer allowlist).
    permanent_interleave_targets = frozenset(
        lex_id
        for lex_id, unit in lexicon.items()
        if str(unit.get("frame_of") or "").startswith(_ARTICLE_FRAME_PREFIX)
    )
    # Each event resolves its OWN pinned scheduler version when one exists
    # (scheduler 3a): a log spanning a scheduler@1 -> scheduler@2 activation
    # must not silently refold everything under today's active version.
    schedules = fold_schedules(
        store,
        scheduler_policy,
        registry=registry,
        permanent_interleave_targets=permanent_interleave_targets,
    )
    automaticity_states: dict[str, AutomaticityState] = (
        fold_automaticity(store, automaticity_policy) if automaticity_policy is not None else {}
    )
    levels = working_levels(
        scores,
        program,
        scoring_policy,
        placement=placement_levels(store, program, scoring_policy),
        placement_writing=placement_writing_level(store, scoring_policy),
    )
    measured = measured_working_level(levels)
    score = learning_score(scores, program, scoring_policy, measured)
    xp = xp_ledger(store, scoring_policy)

    # -- reconstruction texts (curriculum 2d): grouped under their owning topic.
    texts_by_topic: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for text in program.get("texts") or []:
        if isinstance(text, dict) and text.get("topic"):
            texts_by_topic[str(text["topic"])].append(text)
    for group in texts_by_topic.values():
        group.sort(key=lambda text: str(text.get("id")))

    pages: dict[str, str] = {}

    def _schedule_lines(target_id: str) -> list[str]:
        lines = []
        for (ref, dimension), schedule in sorted(schedules.items()):
            if ref == target_id:
                date = schedule.next_review_at.date().isoformat()
                # permanent_interleave (scheduler 3a): an article-tier frame
                # that reached the end of the ladder and never leaves the due
                # queue -- read straight off the schedule, never recomputed.
                marker = " · **постоянный ярус**" if schedule.permanent_interleave else ""
                lines.append(
                    f"- {dimension}: next review [[reviews/{date}]] "
                    f"(interval {schedule.interval_days}d, epoch {schedule.schedule_epoch}){marker}"
                )
        return lines or ["- расписание ещё не открыто"]

    def _automaticity_lines(target_id: str) -> list[str]:
        state = automaticity_states.get(target_id)
        if state is None or state.state == NOT_MEASURED:
            return ["- нет измерений автоматизма"]
        lines = [
            f"- Состояние: **{state.state}**",
            f"- Точность: {_ppm_percent(state.accuracy_ppm)} "
            f"({state.blocks_observed} блок(ов) · {state.sessions_observed} сесси(й))",
        ]
        if state.median_latency_ms is not None:
            baseline = (
                f"{state.baseline_latency_ms} ms" if state.baseline_latency_ms is not None else "нет базы"
            )
            lines.append(f"- Latency: {state.median_latency_ms} ms (база: {baseline})")
        return lines

    def _frame_topic_lines(topic_id: str) -> list[str]:
        frames = frames_by_topic.get(topic_id)
        if not frames:
            return []
        by_tag: dict[str, list[dict[str, Any]]] = defaultdict(list)
        for frame in frames:
            for tag in frame.get("carries") or []:
                by_tag[str(tag)].append(frame)
        lines = ["## Фреймы", ""]
        for tag in sorted(by_tag):
            lines.append(f"### {tag}")
            for frame in sorted(by_tag[tag], key=lambda f: str(f.get("id"))):
                tier = frame.get("tier")
                tier_note = f" (ярус {tier})" if tier is not None else ""
                lines.append(
                    f"- [[{_slug(str(frame.get('id')))}]] — {frame.get('title', frame.get('id'))}{tier_note}"
                )
            lines.append("")
        return lines

    def _text_lines_for_topic(topic_id: str) -> list[str]:
        texts = texts_by_topic.get(topic_id)
        if not texts:
            return []
        lines = ["## Тексты для реконструкции", ""]
        for text in texts:
            lines.append(
                f"- `{text.get('id')}` — {text.get('title', '—')} "
                f"({text.get('domain', '—')} · {text.get('word_count', '—')} слов)"
            )
        lines.append("")
        return lines

    def _mastery_lines(target_id: str) -> tuple[str, str | None, list[str]]:
        state = scores.get(target_id)
        if state is None:
            return "NEW", None, ["- нет оценённых измерений"]
        lines = [f"- {dimension}: {value}" for dimension, value in sorted(state.mastery.items())] or [
            "- нет оценённых измерений"
        ]
        stability = str(state.stability_days) if state.stability_days is not None else None
        return state.knowledge_state, stability, lines

    # -- entity pages: a page per topic and per lexical unit (canon 4: page
    # per entity, independent of whether it has been scored yet).
    for target_id in sorted(topics):
        topic = topics[target_id]
        knowledge_state, stability, mastery_lines = _mastery_lines(target_id)
        body = [
            f"# {target_id}",
            "",
            f"**{topic.get('can_do', '')}**",
            "",
            f"- Уровень: {topic.get('cefr')} · трек: [[{_slug(str(topic.get('track')))}]]",
            f"- Состояние знания: **{knowledge_state}**",
            f"- Stability: {stability} дн." if stability else "- Stability: —",
            "",
            "## Mastery",
            *mastery_lines,
            "",
            "## Автоматизм",
            *_automaticity_lines(target_id),
            "",
            "## Повторения",
            *_schedule_lines(target_id),
            "",
            *_frame_topic_lines(target_id),
            *_text_lines_for_topic(target_id),
        ]
        pages[f"topics/{_slug(target_id)}.md"] = _frontmatter(
            "event-sourced", [target_id], versions
        ) + "\n".join(body)
    for target_id in sorted(lexicon):
        unit = lexicon[target_id]
        knowledge_state, _stability, mastery_lines = _mastery_lines(target_id)
        subdir = "chunks" if "chunk" in str(unit.get("type", "")) else "vocabulary"
        frame_of = unit.get("frame_of")
        body = [
            f"# {unit.get('title', target_id)}",
            "",
            f"- Единица: `{target_id}` ({unit.get('type', '—')})",
            f"- Значение: {unit.get('meaning_ru', '—')}",
        ]
        if frame_of:
            # A frame: the same chunk type, marked as a grammar-form carrier
            # (lexical-system 1c) -- not a new page kind, an enriched one.
            body.append(f"- Фрейм темы: [[{_slug(str(frame_of))}]]")
            carries = unit.get("carries") or []
            if carries:
                carries_str = ", ".join(f"`{tag}`" for tag in carries)
                body.append(f"- Несёт: {carries_str}")
            slot_hint = unit.get("slot_hint_ru")
            if slot_hint:
                body.append(f"- Слот: {slot_hint}")
            tier = unit.get("tier")
            if tier is not None:
                body.append(f"- Ярус: {tier}")
        body += [f"- Состояние знания: **{knowledge_state}**", ""]
        if frame_of:
            examples = unit.get("examples") or []
            if examples:
                body += ["## Примеры", *[f"- {example}" for example in examples], ""]
            contrast = unit.get("contrast")
            if isinstance(contrast, dict) and contrast:
                body += [
                    "## Контраст",
                    f"- {contrast.get('frame', '—')} — {contrast.get('note_ru', '—')}",
                    "",
                ]
            trap = unit.get("trap")
            if isinstance(trap, dict) and trap:
                body += [
                    "## Ловушка",
                    f"- Неверно: {trap.get('learner_form', '—')}",
                    f"- Верно: {trap.get('correction', '—')}",
                    f"- Почему: {trap.get('cause_ru', '—')}",
                    "",
                ]
        body += [
            "## Mastery",
            *mastery_lines,
            "",
            "## Автоматизм",
            *_automaticity_lines(target_id),
            "",
            "## Повторения",
            *_schedule_lines(target_id),
            "",
        ]
        pages[f"knowledge/{subdir}/{_slug(target_id)}.md"] = _frontmatter(
            "event-sourced", [target_id], versions
        ) + "\n".join(body)

    # -- sessions and plans (SQLite-authoritative operational state)
    for session_id, session, _ in sorted(sessions, key=lambda row: row[0]):
        manifest = session.get("manifest") or {}
        started = str(manifest.get("started_at", ""))[:10] or "0000-00-00"
        year = started[:4]
        plan_info = plans.get(session_id)
        step_lines: list[str] = []
        if plan_info is not None:
            for step in plan_info[1].get("steps", []):
                mark = "x" if step.get("presented_at") else " "
                target = step.get("target_ref") or "free conversation"
                link = f"[[{_slug(str(target))}]]" if step.get("target_ref") else target
                step_lines.append(f"- [{mark}] {step.get('bucket')}/{step.get('step_type')}: {link}")
        body = [
            f"# Сессия {started} · {session_id}",
            "",
            f"- Статус: **{session.get('status')}** · провайдер: {manifest.get('provider', '—')}",
            f"- Попыток записано: {attempts_by_session.get(session_id, 0)}",
            f"- План: [[{_slug(session_id)}-plan]]",
            "",
            "## Шаги",
            *(step_lines or ["- план пуст"]),
            "",
        ]
        pages[f"sessions/{year}/{started}-{_slug(session_id)}.md"] = _frontmatter(
            "operational", [session_id], versions
        ) + "\n".join(body)
        if plan_info is not None:
            plan_id, plan = plan_info
            remaining = plan.get("ledger", {}).get("remaining_seconds")
            body = [
                f"# План сессии {session_id}",
                "",
                f"- Ревизия композиции: {plan.get('composition_revision')}",
                f"- Версия плана: {plan.get('plan_version')}",
                f"- Бюджет: {plan.get('total_seconds')} сек. · осталось: {remaining} сек.",
                f"- Waivers: {', '.join(plan.get('waivers', [])) or '—'}",
                "",
            ]
            pages[f"plans/{_slug(session_id)}-plan.md"] = _frontmatter(
                "operational", [plan_id, session_id], versions
            ) + "\n".join(body)

    # -- reviews by date (event-sourced schedule projection: schedules are a
    # pure fold over the event log, not SQLite-authoritative operational state)
    by_date: dict[str, list[str]] = defaultdict(list)
    for (target_id, dimension), schedule in sorted(schedules.items()):
        marker = " · постоянный ярус" if schedule.permanent_interleave else ""
        by_date[schedule.next_review_at.date().isoformat()].append(
            f"- [[{_slug(target_id)}]] · {dimension} (интервал {schedule.interval_days}д){marker}"
        )
    for date, lines in sorted(by_date.items()):
        pages[f"reviews/{date}.md"] = _frontmatter(
            "event-sourced", [f"reviews:{date}"], versions
        ) + "\n".join([f"# Повторения на {date}", "", *lines, ""])

    # -- dashboards
    skill_lines = [
        f"- **{skill}**: {info['level'] or 'no-data'} (confidence {info['confidence']}, "
        f"источник {info['basis'] or 'нет данных'}, {info['active_topics']} активных тем"
        + (" · предварительно)" if info["provisional"] else ")")
        for skill, info in sorted(levels.items())
    ]
    pages["current/current-level.md"] = _frontmatter("event-sourced", ["scores"], versions) + "\n".join(
        [
            "# Текущий уровень",
            "",
            f"- Измеренный рабочий уровень: **{measured or 'no-data'}** (не выше слабейшего навыка)",
            f"- Learning Score: **{score or 'no-data'}**",
            "",
            "## Навыки",
            *skill_lines,
            "",
        ]
    )

    # -- automaticity dashboard (scoring 3d): every target in the program gets
    # an entry, defaulting to `not_measured` -- the axis is total, not just
    # the targets that happen to have a drill block yet.
    automaticity_buckets: dict[str, list[tuple[str, AutomaticityState]]] = defaultdict(list)
    for target_id in sorted(set(topics) | set(lexicon)):
        axis_state = automaticity_states.get(target_id) or AutomaticityState()
        automaticity_buckets[axis_state.state].append((target_id, axis_state))
    automaticity_dashboard_lines = [
        "# Автоматизм",
        "",
        *(
            f"- **{state_name}**: {len(automaticity_buckets.get(state_name, []))}"
            for state_name in (AUTOMATIC, PROCEDURALIZED, DELIBERATE, NOT_MEASURED)
        ),
        "",
    ]
    for state_name in (AUTOMATIC, PROCEDURALIZED, DELIBERATE):
        entries = sorted(automaticity_buckets.get(state_name, []), key=lambda entry: entry[0])
        automaticity_dashboard_lines.append(f"## {state_name}")
        if not entries:
            automaticity_dashboard_lines.append("- пока пусто")
        else:
            for target_id, axis_state in entries:
                latency = "—"
                if axis_state.median_latency_ms is not None:
                    baseline = "нет базы"
                    if axis_state.baseline_latency_ms:
                        baseline = f"{axis_state.baseline_latency_ms} ms"
                    latency = f"{axis_state.median_latency_ms} ms (база {baseline})"
                automaticity_dashboard_lines.append(
                    f"- [[{_slug(target_id)}]] · {_ppm_percent(axis_state.accuracy_ppm)} · "
                    f"{axis_state.blocks_observed} блок(ов)/{axis_state.sessions_observed} "
                    f"сесси(й) · latency {latency}"
                )
        automaticity_dashboard_lines.append("")
    pages["current/automaticity.md"] = _frontmatter("event-sourced", ["automaticity"], versions) + "\n".join(
        automaticity_dashboard_lines
    )

    counts: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    for topic_id, topic in topics.items():
        state = scores.get(topic_id)
        knowledge = state.knowledge_state if state else "NEW"
        counts[str(topic.get("cefr"))][knowledge] += 1
    progress_lines = []
    for level in ("A1", "A2", "B1", "B2", "C1", "C2"):
        row = counts.get(level, {})
        total = sum(row.values())
        touched = total - row.get("NEW", 0)
        progress_lines.append(
            f"- **{level}**: {total} тем · затронуто {touched} · "
            f"ACTIVE+ {row.get('ACTIVE', 0) + row.get('MASTERED', 0)}"
        )
    pages["current/roadmap-progress.md"] = _frontmatter("event-sourced", ["scores"], versions) + "\n".join(
        ["# Прогресс по программе", "", *progress_lines, ""]
    )

    upcoming = sorted(by_date.items())[:5]
    next_lines = [f"- [[{date}]] — {len(items)} целей" for date, items in upcoming]
    pages["current/next-session.md"] = _frontmatter("event-sourced", ["schedules"], versions) + "\n".join(
        [
            "# Следующая сессия",
            "",
            "## Ближайшие повторения",
            *(next_lines or ["- расписаний ещё нет"]),
            "",
        ]
    )

    vocab_lines = [
        f"- [[{_slug(target_id)}]] · {dimension}: {schedule.next_review_at.date().isoformat()}"
        + (" · **постоянный ярус**" if schedule.permanent_interleave else "")
        for (target_id, dimension), schedule in sorted(schedules.items())
        if target_id in lexicon
    ]
    # permanent_interleave targets (scheduler 3a, PD-F): article-tier frames
    # that never leave the due queue, even past MASTERED -- marked per line
    # above and summed here so the count is visible without scanning the list.
    permanent_interleave_count = sum(1 for schedule in schedules.values() if schedule.permanent_interleave)
    pages["current/vocabulary-review.md"] = _frontmatter(
        "event-sourced", ["schedules"], versions
    ) + "\n".join(
        [
            "# Лексика к повторению",
            "",
            f"- Постоянный ярус (не покидает очередь): {permanent_interleave_count}",
            "",
            *(vocab_lines or ["- пока нечего повторять"]),
            "",
        ]
    )

    pages["current/recurring-errors.md"] = _frontmatter("event-sourced", ["errors"], versions) + "\n".join(
        [
            "# Повторяющиеся ошибки",
            "",
            "- данных ещё нет: наблюдение ошибок (`ERROR_OBSERVED`) появится в control-доводке (2.8)",
            "",
        ]
    )

    pages["current/learner-profile.md"] = _frontmatter(
        "operational", ["sessions", "xp"], versions
    ) + "\n".join(
        [
            "# Профиль",
            "",
            f"- Сессий: {len(sessions)}",
            f"- XP: **{xp['total']}** за {xp['practice_days']} дн. практики · streak {xp['streak']}",
            f"- Программа: {len(topics)} тем · {len(lexicon)} лекс. единиц (curriculum {curriculum_version})",
            "",
        ]
    )

    # -- the learner's personal lexicon (layer 3): a readable projection.
    # A pure fold over the event log (memory must not import learner),
    # de-duplicated by logical identity, ordered deterministically. Adding a
    # word is enrollment, never knowledge -- the page says so, and re-rendering
    # unchanged state is byte-identical (no wall clock).
    seen_lexicon: set[str] = set()
    personal_entries: list[dict[str, Any]] = []
    for event in store.read():
        if event.type != LEARNER_LEXICON_ENTRY_ADDED:
            continue
        key = str(event.payload.get("identity_key"))
        if key in seen_lexicon:
            continue
        seen_lexicon.add(key)
        personal_entries.append(dict(event.payload))
    personal_entries.sort(key=lambda entry: (str(entry.get("added_at")), str(entry.get("entry_id"))))
    entry_lines: list[str] = []
    for entry in personal_entries:
        linked = entry.get("linked_item_id")
        link = f" · [[{_slug(str(linked))}]]" if linked else " · (нет в программе)"
        note = f" — {entry['note_ru']}" if entry.get("note_ru") else ""
        entry_lines.append(f"- **{entry.get('surface')}** [{entry.get('source')}]{note}{link}")
    pages["knowledge/personal-lexicon.md"] = _frontmatter(
        "event-sourced", ["personal-lexicon"], versions
    ) + "\n".join(
        [
            "# Личный словарь",
            "",
            "Заметки ученика (слой 3). Добавление слова — это enrollment, не evidence:",
            "перевод или объяснение не создаёт знание и не меняет Mastery.",
            "",
            *(entry_lines or ["- пока пусто"]),
            "",
        ]
    )

    return pages


# -- IO around the pure renderer ---------------------------------------------


def render(store: EventStore, registry: PolicyRegistry, memory_dir: Any) -> dict[str, Any]:
    """Write the projection into ``memory/``; returns written/unchanged counts."""
    from pathlib import Path

    root = Path(memory_dir)
    pages = render_pages(store, registry)
    written, unchanged = [], 0
    for relative, content in sorted(pages.items()):
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        data = content.encode("utf-8")
        if path.exists() and path.read_bytes() == data:
            unchanged += 1
            continue
        path.write_bytes(data)
        written.append(relative)
    return {
        "pages": len(pages),
        "written": written,
        "unchanged": unchanged,
        "content_hash": payload_hash({k: pages[k] for k in sorted(pages)}),
    }


def rebuild(store: EventStore, registry: PolicyRegistry, memory_dir: Any) -> dict[str, Any]:
    """Full regenerate + orphan removal: memory/ ends exactly at the render set."""
    from pathlib import Path

    root = Path(memory_dir)
    report = render(store, registry, memory_dir)
    expected = set(render_pages(store, registry))
    removed = []
    if root.is_dir():
        for path in sorted(root.rglob("*.md")):
            relative = path.relative_to(root).as_posix()
            if relative not in expected:
                path.unlink()
                removed.append(relative)
    return {**report, "removed": removed}


def check(store: EventStore, registry: PolicyRegistry, memory_dir: Any) -> dict[str, Any]:
    """Drift check of the generated zone only. Read-only: repairs nothing."""
    from pathlib import Path

    root = Path(memory_dir)
    pages = render_pages(store, registry)
    drifted, missing, extra = [], [], []
    for relative, content in sorted(pages.items()):
        path = root / relative
        if not path.exists():
            missing.append(relative)
        elif path.read_bytes() != content.encode("utf-8"):
            drifted.append(relative)
    if root.is_dir():
        for path in sorted(root.rglob("*.md")):
            relative = path.relative_to(root).as_posix()
            if relative not in pages:
                extra.append(relative)
    return {
        "ok": not (drifted or missing or extra),
        "drifted": drifted,
        "missing": missing,
        "extra": extra,
        "pages": len(pages),
    }


def emit_projection_updated(
    store: EventStore,
    clock: Clock,
    random_source: RandomSource,
    report: dict[str, Any],
    *,
    actor: str = "engine",
) -> None:
    """Publish the update fact (post-commit projection; canon 6)."""
    with UnitOfWork(store, clock) as uow:
        uow.append(
            [
                make_event(
                    id=new_ulid(clock, random_source),
                    type=EVENT_PROJECTION_UPDATED,
                    occurred_at=clock.now(),
                    actor=actor,
                    correlation_id=new_ulid(clock, random_source),
                    payload={
                        "pages": report["pages"],
                        "written": len(report.get("written", [])),
                        "removed": len(report.get("removed", [])),
                        "content_hash": report["content_hash"],
                    },
                )
            ]
        )
