"""Deterministic post-pass for the automaticity layer: link every frame
(``curriculum/lexicon/frames-*.yaml`` item with ``frame_of``) to its topic.

Two authoritative-format edits, both textual so comments and flow style survive:

* ``curriculum/lexicon/_suggested-topic-links.yaml`` gets one advisory link per
  frame that has none (the lexicon invariants require a link for every chunk);
* the topic's ``lexicon: [...]`` line in ``curriculum/topics/<level>.yaml`` gets
  the frame ids appended (``topic.lexicon`` is the owner of the link).

Idempotent: re-running adds nothing. ``--check`` only reports what would change.
Usage: ``python3 tools/link_frames.py [--check]``.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent / "curriculum"
LINKS = ROOT / "lexicon" / "_suggested-topic-links.yaml"
TOPIC_FILES = ("a1.yaml", "a2.yaml", "b1.yaml", "b2.yaml", "c1.yaml", "c2.yaml")
SECTION = "  # ===== frames (automaticity layer, generated by tools/link_frames.py) ====="


def load_frames() -> dict[str, list[str]]:
    """Return ``{topic_id: [frame_id, ...]}`` in sorted, deterministic order."""
    by_topic: dict[str, list[str]] = {}
    for path in sorted((ROOT / "lexicon").glob("frames-*.yaml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        for item in data.get("lexical_items", []):
            topic = item.get("frame_of")
            if topic:
                by_topic.setdefault(str(topic), []).append(str(item["id"]))
    return {topic: sorted(ids) for topic, ids in sorted(by_topic.items())}


def update_links(frames: dict[str, list[str]], check: bool) -> int:
    text = LINKS.read_text(encoding="utf-8")
    linked = set(re.findall(r"lexical_item: ([a-z0-9.-]+)", text))
    new_lines = [
        f"  - {{lexical_item: {frame_id}, topics: [{topic}]}}"
        for topic, ids in frames.items()
        for frame_id in ids
        if frame_id not in linked
    ]
    if new_lines and not check:
        block = "\n".join(new_lines) + "\n"
        if SECTION in text:
            text = text.rstrip("\n") + "\n" + block
        else:
            text = text.rstrip("\n") + "\n\n" + SECTION + "\n" + block
        LINKS.write_text(text, encoding="utf-8")
    return len(new_lines)


def update_topics(frames: dict[str, list[str]], check: bool) -> int:
    added = 0
    for name in TOPIC_FILES:
        path = ROOT / "topics" / name
        if not path.is_file():
            continue
        lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
        current: str | None = None
        changed = False
        for index, line in enumerate(lines):
            id_match = re.match(r"^  - id: (\S+)\s*$", line)
            if id_match:
                current = id_match.group(1)
                continue
            lex_match = re.match(r"^(    lexicon: \[)(.*)(\]\s*)$", line)
            if not lex_match or current not in frames:
                continue
            existing = [part.strip() for part in lex_match.group(2).split(",") if part.strip()]
            missing = [frame_id for frame_id in frames[current] if frame_id not in existing]
            if not missing:
                continue
            added += len(missing)
            merged = ", ".join([*existing, *missing])
            lines[index] = f"{lex_match.group(1)}{merged}{lex_match.group(3)}"
            changed = True
        if changed and not check:
            path.write_text("".join(lines), encoding="utf-8")
    return added


def main(argv: list[str]) -> int:
    check = "--check" in argv
    frames = load_frames()
    total = sum(len(ids) for ids in frames.values())
    links_added = update_links(frames, check)
    topic_refs_added = update_topics(frames, check)
    verb = "would add" if check else "added"
    print(
        f"frames: {total} across {len(frames)} topics; {verb} {links_added} advisory links "
        f"and {topic_refs_added} topic.lexicon refs"
    )
    unknown = [topic for topic in frames if not _topic_exists(topic)]
    if unknown:
        print("frame_of targets without a topic body: " + ", ".join(unknown))
        return 1
    return 0


def _topic_exists(topic_id: str) -> bool:
    for name in TOPIC_FILES:
        path = ROOT / "topics" / name
        if path.is_file() and re.search(
            rf"^  - id: {re.escape(topic_id)}\s*$", path.read_text(encoding="utf-8"), re.M
        ):
            return True
    return False


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
